name: hidroly
description: "A new Flutter project."
publish_to: 'none'
version: 2.1.1+19

environment:
  sdk: ^3.11.0

dependencies:
  awesome_notifications: ^0.11.0
  collection: ^1.19.1
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  easy_localization: ^3.0.8
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.1
  freezed: ^3.2.5
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  graphic: ^2.7.0
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5
  result_dart: ^2.2.0
  riverpod: ^3.2.1
  riverpod_annotation: ^4.0.2
  shared_preferences: ^2.5.4
  shared_preferences_platform_interface: ^2.4.2
  url_launcher: ^6.3.2
  workmanager: ^0.9.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.11.1
  drift_dev: ^2.31.0
  test: ^1.29.0

flutter:
  assets:
    - assets/translations/
  uses-material-design: true
